package Couchbase::Client::Errors;
# This module was generated automatically by ExtUtils::H2PM from error_constants.pl

push @EXPORT, 'COUCHBASE_SUCCESS', 'COUCHBASE_AUTH_CONTINUE', 'COUCHBASE_AUTH_ERROR', 'COUCHBASE_DELTA_BADVAL', 'COUCHBASE_E2BIG', 'COUCHBASE_EBUSY', 'COUCHBASE_EINTERNAL', 'COUCHBASE_EINVAL', 'COUCHBASE_ENOMEM', 'COUCHBASE_ERANGE', 'COUCHBASE_ERROR', 'COUCHBASE_ETMPFAIL', 'COUCHBASE_KEY_EEXISTS', 'COUCHBASE_KEY_ENOENT', 'COUCHBASE_LIBEVENT_ERROR', 'COUCHBASE_NETWORK_ERROR', 'COUCHBASE_NOT_MY_VBUCKET', 'COUCHBASE_NOT_STORED', 'COUCHBASE_NOT_SUPPORTED', 'COUCHBASE_UNKNOWN_COMMAND', 'COUCHBASE_UNKNOWN_HOST', 'COUCHBASE_PROTOCOL_ERROR', 'COUCHBASE_ETIMEDOUT', 'COUCHBASE_CONNECT_ERROR', 'COUCHBASE_BUCKET_ENOENT';
use constant COUCHBASE_SUCCESS => 0;
use constant COUCHBASE_AUTH_CONTINUE => 1;
use constant COUCHBASE_AUTH_ERROR => 2;
use constant COUCHBASE_DELTA_BADVAL => 3;
use constant COUCHBASE_E2BIG => 4;
use constant COUCHBASE_EBUSY => 5;
use constant COUCHBASE_EINTERNAL => 6;
use constant COUCHBASE_EINVAL => 7;
use constant COUCHBASE_ENOMEM => 8;
use constant COUCHBASE_ERANGE => 9;
use constant COUCHBASE_ERROR => 10;
use constant COUCHBASE_ETMPFAIL => 11;
use constant COUCHBASE_KEY_EEXISTS => 12;
use constant COUCHBASE_KEY_ENOENT => 13;
use constant COUCHBASE_LIBEVENT_ERROR => 14;
use constant COUCHBASE_NETWORK_ERROR => 15;
use constant COUCHBASE_NOT_MY_VBUCKET => 16;
use constant COUCHBASE_NOT_STORED => 17;
use constant COUCHBASE_NOT_SUPPORTED => 18;
use constant COUCHBASE_UNKNOWN_COMMAND => 19;
use constant COUCHBASE_UNKNOWN_HOST => 20;
use constant COUCHBASE_PROTOCOL_ERROR => 21;
use constant COUCHBASE_ETIMEDOUT => 22;
use constant COUCHBASE_CONNECT_ERROR => 23;
use constant COUCHBASE_BUCKET_ENOENT => 24;

1;
